import type { AuthenticatedUser } from '../auth/interfaces/authenticated-user.interface';
import { PrismaService } from '../prisma/prisma.service';
import { CreateJnvPrincipalDto } from './dto/create-jnv-principal.dto';
import { UpdateJnvPrincipalDto } from './dto/update-jnv-principal.dto';
export declare class JnvPrincipalsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    create(organizationId: number, dto: CreateJnvPrincipalDto, file: Express.Multer.File | undefined, actor: AuthenticatedUser): Promise<{
        id: number;
        organizationId: number;
        principalNameEnglish: string;
        principalNameHindi: string | null;
        principalDesignationEnglish: string | null;
        principalDesignationHindi: string | null;
        email: string | null;
        mobile: string | null;
        messageEnglish: string | null;
        messageHindi: string | null;
        pictureUrl: string | null;
        mimeType: string | null;
        extension: string | null;
        fileSize: string | null;
        joinedAt: Date;
        relievedAt: Date | null;
        displayOrder: number;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    findAll(organizationId: number): Promise<{
        id: number;
        organizationId: number;
        principalNameEnglish: string;
        principalNameHindi: string | null;
        principalDesignationEnglish: string | null;
        principalDesignationHindi: string | null;
        email: string | null;
        mobile: string | null;
        messageEnglish: string | null;
        messageHindi: string | null;
        pictureUrl: string | null;
        mimeType: string | null;
        extension: string | null;
        fileSize: string | null;
        joinedAt: Date;
        relievedAt: Date | null;
        displayOrder: number;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    findOne(organizationId: number, id: number): Promise<{
        id: number;
        organizationId: number;
        principalNameEnglish: string;
        principalNameHindi: string | null;
        principalDesignationEnglish: string | null;
        principalDesignationHindi: string | null;
        email: string | null;
        mobile: string | null;
        messageEnglish: string | null;
        messageHindi: string | null;
        pictureUrl: string | null;
        mimeType: string | null;
        extension: string | null;
        fileSize: string | null;
        joinedAt: Date;
        relievedAt: Date | null;
        displayOrder: number;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    update(organizationId: number, id: number, dto: UpdateJnvPrincipalDto, actor: AuthenticatedUser): Promise<{
        id: number;
        organizationId: number;
        principalNameEnglish: string;
        principalNameHindi: string | null;
        principalDesignationEnglish: string | null;
        principalDesignationHindi: string | null;
        email: string | null;
        mobile: string | null;
        messageEnglish: string | null;
        messageHindi: string | null;
        pictureUrl: string | null;
        mimeType: string | null;
        extension: string | null;
        fileSize: string | null;
        joinedAt: Date;
        relievedAt: Date | null;
        displayOrder: number;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    replaceImage(organizationId: number, id: number, file: Express.Multer.File, actor: AuthenticatedUser): Promise<{
        id: number;
        organizationId: number;
        principalNameEnglish: string;
        principalNameHindi: string | null;
        principalDesignationEnglish: string | null;
        principalDesignationHindi: string | null;
        email: string | null;
        mobile: string | null;
        messageEnglish: string | null;
        messageHindi: string | null;
        pictureUrl: string | null;
        mimeType: string | null;
        extension: string | null;
        fileSize: string | null;
        joinedAt: Date;
        relievedAt: Date | null;
        displayOrder: number;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    remove(organizationId: number, id: number, actor: AuthenticatedUser): Promise<{
        id: number;
        organizationId: number;
        principalNameEnglish: string;
        principalNameHindi: string | null;
        principalDesignationEnglish: string | null;
        principalDesignationHindi: string | null;
        email: string | null;
        mobile: string | null;
        messageEnglish: string | null;
        messageHindi: string | null;
        pictureUrl: string | null;
        mimeType: string | null;
        extension: string | null;
        fileSize: string | null;
        joinedAt: Date;
        relievedAt: Date | null;
        displayOrder: number;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    }>;
    findPublicCurrent(organizationId: number): Promise<{
        id: number;
        organization_id: number;
        principal_name_english: string;
        principal_name_hindi: string | null;
        principal_designation_english: string | null;
        principal_designation_hindi: string | null;
        email: string | null;
        mobile: string | null;
        message_english: string | null;
        message_hindi: string | null;
        picture_url: string | null;
        joined_at: Date;
        relieved_at: Date | null;
        display_order: number;
    }>;
    findPublicHistory(organizationId: number): Promise<{
        id: number;
        organization_id: number;
        principal_name_english: string;
        principal_name_hindi: string | null;
        principal_designation_english: string | null;
        principal_designation_hindi: string | null;
        email: string | null;
        mobile: string | null;
        message_english: string | null;
        message_hindi: string | null;
        picture_url: string | null;
        joined_at: Date;
        relieved_at: Date | null;
        display_order: number;
    }[]>;
    imageStream(organizationId: number, id: number, publicOnly?: boolean): Promise<{
        stream: import("fs").ReadStream;
        mimeType: string;
    }>;
    cleanupUploadedFile(file: Express.Multer.File): Promise<void>;
    private ensureJnv;
    private findExisting;
    private ensureTenure;
    private fileData;
    private absolutePath;
    private deleteStoredFile;
    private toResponse;
    private toPublicResponse;
}
