import type { Response } from 'express';
import type { AuthenticatedUser } from '../auth/interfaces/authenticated-user.interface';
import { CreateJnvPrincipalDto } from './dto/create-jnv-principal.dto';
import { UpdateJnvPrincipalDto } from './dto/update-jnv-principal.dto';
import { JnvPrincipalsService } from './jnv-principals.service';
export declare class JnvPrincipalsController {
    private readonly principals;
    constructor(principals: JnvPrincipalsService);
    create(organizationId: number, dto: CreateJnvPrincipalDto, file: Express.Multer.File | undefined, user: AuthenticatedUser): Promise<{
        message: string;
        data: {
            id: number;
            organizationId: number;
            principalNameEnglish: string;
            principalNameHindi: string | null;
            principalDesignationEnglish: string | null;
            principalDesignationHindi: string | null;
            email: string | null;
            mobile: string | null;
            messageEnglish: string | null;
            messageHindi: string | null;
            pictureUrl: string | null;
            mimeType: string | null;
            extension: string | null;
            fileSize: string | null;
            joinedAt: Date;
            relievedAt: Date | null;
            displayOrder: number;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
    }>;
    findAll(organizationId: number): Promise<{
        message: string;
        data: {
            id: number;
            organizationId: number;
            principalNameEnglish: string;
            principalNameHindi: string | null;
            principalDesignationEnglish: string | null;
            principalDesignationHindi: string | null;
            email: string | null;
            mobile: string | null;
            messageEnglish: string | null;
            messageHindi: string | null;
            pictureUrl: string | null;
            mimeType: string | null;
            extension: string | null;
            fileSize: string | null;
            joinedAt: Date;
            relievedAt: Date | null;
            displayOrder: number;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        }[];
    }>;
    image(organizationId: number, id: number, response: Response): Promise<void>;
    findOne(organizationId: number, id: number): Promise<{
        message: string;
        data: {
            id: number;
            organizationId: number;
            principalNameEnglish: string;
            principalNameHindi: string | null;
            principalDesignationEnglish: string | null;
            principalDesignationHindi: string | null;
            email: string | null;
            mobile: string | null;
            messageEnglish: string | null;
            messageHindi: string | null;
            pictureUrl: string | null;
            mimeType: string | null;
            extension: string | null;
            fileSize: string | null;
            joinedAt: Date;
            relievedAt: Date | null;
            displayOrder: number;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
    }>;
    update(organizationId: number, id: number, dto: UpdateJnvPrincipalDto, user: AuthenticatedUser): Promise<{
        message: string;
        data: {
            id: number;
            organizationId: number;
            principalNameEnglish: string;
            principalNameHindi: string | null;
            principalDesignationEnglish: string | null;
            principalDesignationHindi: string | null;
            email: string | null;
            mobile: string | null;
            messageEnglish: string | null;
            messageHindi: string | null;
            pictureUrl: string | null;
            mimeType: string | null;
            extension: string | null;
            fileSize: string | null;
            joinedAt: Date;
            relievedAt: Date | null;
            displayOrder: number;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
    }>;
    replaceImage(organizationId: number, id: number, file: Express.Multer.File | undefined, user: AuthenticatedUser): Promise<{
        message: string;
        data: {
            id: number;
            organizationId: number;
            principalNameEnglish: string;
            principalNameHindi: string | null;
            principalDesignationEnglish: string | null;
            principalDesignationHindi: string | null;
            email: string | null;
            mobile: string | null;
            messageEnglish: string | null;
            messageHindi: string | null;
            pictureUrl: string | null;
            mimeType: string | null;
            extension: string | null;
            fileSize: string | null;
            joinedAt: Date;
            relievedAt: Date | null;
            displayOrder: number;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
    }>;
    remove(organizationId: number, id: number, user: AuthenticatedUser): Promise<{
        message: string;
        data: {
            id: number;
            organizationId: number;
            principalNameEnglish: string;
            principalNameHindi: string | null;
            principalDesignationEnglish: string | null;
            principalDesignationHindi: string | null;
            email: string | null;
            mobile: string | null;
            messageEnglish: string | null;
            messageHindi: string | null;
            pictureUrl: string | null;
            mimeType: string | null;
            extension: string | null;
            fileSize: string | null;
            joinedAt: Date;
            relievedAt: Date | null;
            displayOrder: number;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
    }>;
}
