import { createReadStream } from 'node:fs';
import type { AuthenticatedUser } from '../auth/interfaces/authenticated-user.interface';
import { OrganizationOwnershipService } from '../auth/services/organization-ownership.service';
import { PaginatedResponseDto } from '../common/dto/paginated-response.dto';
import { PrismaService } from '../prisma/prisma.service';
import { CreateExternalMediaDto } from './dto/create-external-media.dto';
import { GetMediaQueryDto } from './dto/get-media-query.dto';
import { GetPublicMediaQueryDto } from './dto/get-public-media-query.dto';
import { MediaResponseDto } from './dto/media-response.dto';
import { PublicMediaResponseDto } from './dto/public-media-response.dto';
import { UpdateMediaDto } from './dto/update-media.dto';
import { UploadMediaDto } from './dto/upload-media.dto';
type ImportantLinkField = 'importantLink1' | 'importantLink2' | 'importantLink3';
export declare class MediaService {
    private readonly prisma;
    private readonly ownership;
    constructor(prisma: PrismaService, ownership: OrganizationOwnershipService);
    createExternal(dto: CreateExternalMediaDto, actor: AuthenticatedUser): Promise<MediaResponseDto>;
    upload(dto: UploadMediaDto, file: Express.Multer.File, hindiFile: Express.Multer.File | undefined, actor: AuthenticatedUser): Promise<MediaResponseDto>;
    findAll(query: GetMediaQueryDto, actor: AuthenticatedUser): Promise<PaginatedResponseDto<MediaResponseDto & {
        organization_name: string;
    }>>;
    findOne(id: number, actor: AuthenticatedUser): Promise<MediaResponseDto>;
    download(id: number, actor: AuthenticatedUser): Promise<{
        stream: ReturnType<typeof createReadStream>;
        filename: string;
        mimeType: string;
    }>;
    downloadHindi(id: number, actor: AuthenticatedUser): Promise<{
        stream: ReturnType<typeof createReadStream>;
        filename: string;
        mimeType: string;
    }>;
    update(id: number, dto: UpdateMediaDto, actor: AuthenticatedUser): Promise<MediaResponseDto>;
    replaceFile(id: number, file: Express.Multer.File, actor: AuthenticatedUser, isHindiFile?: boolean): Promise<MediaResponseDto>;
    remove(id: number, actor: AuthenticatedUser): Promise<MediaResponseDto>;
    restore(id: number, actor: AuthenticatedUser): Promise<MediaResponseDto>;
    cleanupUploadedFiles(files: Array<Express.Multer.File | undefined>): Promise<void>;
    cleanupUploadedFile(file?: Express.Multer.File): Promise<void>;
    findPublic(query: GetPublicMediaQueryDto): Promise<PaginatedResponseDto<PublicMediaResponseDto>>;
    findImportantLinks(query: GetPublicMediaQueryDto, importantLink: ImportantLinkField): Promise<PaginatedResponseDto<PublicMediaResponseDto>>;
    publicDownload(id: number, organizationId?: number): Promise<{
        stream: ReturnType<typeof createReadStream>;
        filename: string;
        mimeType: string;
    }>;
    publicDownloadHindi(id: number, organizationId?: number): Promise<{
        stream: ReturnType<typeof createReadStream>;
        filename: string;
        mimeType: string;
    }>;
    private findActiveMedia;
    private findViewableMedia;
    private assertDateRange;
    private ensureActiveMediaType;
    private resolveSharedMediaTypeIds;
    private sharedMediaPlacementNames;
    private sharedMediaPlacements;
    private ensureActiveOrganization;
    private resolveVisibility;
    private normalizeRoIds;
    private normalizeJnvIds;
    private ensureHeadquartersSelectiveSharing;
    private ensureRegionalOffices;
    private ensureJnvOrganizations;
    private buildWhere;
    private visibilityWhere;
    private exactRoIdsWhere;
    private exactJnvIdsWhere;
    private mediaTypeMatchWhere;
    private publicWhere;
    private headquartersSelectiveWhere;
    private orderBy;
    private createAuditLog;
    private toResponse;
    private toAuditValues;
    private toPublicResponse;
    private mediaFileData;
    private hindiMediaFileData;
    private checksum;
    private assertDownloadableFile;
    private hindiFileData;
    private sanitizeFilename;
    private extensionOf;
    private toStoredPath;
    private absolutePath;
    private removePhysicalFile;
}
export {};
