import { SharedMediaPlacementDto } from './shared-media-placement.dto';

export class MediaResponseDto {
  id: number;
  organizationId: number;
  mediaTypeId: number;
  mediaTypeName: string | null;
  sharedMediaTypeIds: string | null;
  shared_media_placements: SharedMediaPlacementDto[];
  titleEnglish: string;
  titleHindi: string | null;
  descriptionEnglish: string | null;
  descriptionHindi: string | null;
  originalFilename: string;
  mimeType: string;
  extension: string;
  fileSize: string;
  checksum: string | null;
  hindiOriginalFilename: string | null;
  hindiMimeType: string | null;
  hindiExtension: string | null;
  hindiFileSize: string | null;
  hindiChecksum: string | null;
  hindiDownloadUrl: string | null;
  display_order: number;
  is_active: boolean;
  is_new: boolean | null;
  visible_to_all: boolean | null;
  ro_ids: string | null;
  jnv_ids: string | null;
  important_link_1: boolean | null;
  important_link_2: boolean | null;
  important_link_3: boolean | null;
  start_date: string | null;
  end_date: string | null;
  uploadedAt: Date;
  createdAt: Date;
  updatedAt: Date;
  isDeleted: boolean;
}
